"""
CrowdStrike Falcon - Alert Triage
-----------------------------------
Reads recent alerts, then updates their status and adds a comment,
closing the loop from detection to response via API.

This mirrors the same triage step done manually in the Sentinel lab
(closing incidents as Benign Positive with a note) — here it's done
programmatically instead of through the console.

Setup:
    pip install crowdstrike-falconpy

Environment variables required:
    FALCON_CLIENT_ID
    FALCON_CLIENT_SECRET

Required API scope: Alerts (Read + Write)
"""

import os
import sys
from falconpy import Alerts


def get_credentials():
    client_id = os.environ.get("FALCON_CLIENT_ID")
    client_secret = os.environ.get("FALCON_CLIENT_SECRET")

    if not client_id or not client_secret:
        print("Error: FALCON_CLIENT_ID and FALCON_CLIENT_SECRET must be set as environment variables.")
        sys.exit(1)

    return client_id, client_secret


def triage_recent_alerts(limit=10):
    client_id, client_secret = get_credentials()
    falcon = Alerts(client_id=client_id, client_secret=client_secret)

    # 1. Fetch recent alerts
    response = falcon.get_alerts_combined(limit=limit, sort="created_timestamp|desc")

    if response["status_code"] != 200:
        print("Failed to retrieve alerts:", response["body"].get("errors"))
        sys.exit(1)

    alerts = response["body"]["resources"]

    if not alerts:
        print("No alerts found to triage.")
        return

    alert_ids = [a["composite_id"] for a in alerts]
    print(f"Found {len(alert_ids)} alert(s) to triage.\n")

    # 2. Update status + add a comment explaining the context
    # Note: valid update_status values are "new", "in_progress", "reopened",
    # "closed" — confirmed directly from the API's error response, since
    # the public docs listed different (outdated) values.
    update_response = falcon.update_alerts_v3(
        composite_ids=alert_ids,
        update_status="closed",
        append_comment=(
            "Reviewed - true positive. Detection confirmed accurate. "
            "Generated by an authorized, controlled test using Atomic "
            "Red Team (MITRE T1053.005 - Scheduled Task/Job). No real "
            "threat — closing as part of a security engineering lab "
            "exercise."
        ),
    )

    if update_response["status_code"] not in (200, 207):
        print("Failed to update alerts:", update_response["body"].get("errors"))
        sys.exit(1)

    print(f"Successfully triaged {len(alert_ids)} alert(s):")
    for aid in alert_ids:
        print(f"  - {aid}")


if __name__ == "__main__":
    triage_recent_alerts(limit=10)
